//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCEDL.GUI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QCEDL.GUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string StorageType {
            get {
                return ResourceManager.GetString("StorageType", resourceCulture);
            }
        }
        
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        public static string Provision {
            get {
                return ResourceManager.GetString("Provision", resourceCulture);
            }
        }
        
        public static string RawProgram {
            get {
                return ResourceManager.GetString("RawProgram", resourceCulture);
            }
        }
        
        public static string PrintGpt {
            get {
                return ResourceManager.GetString("PrintGpt", resourceCulture);
            }
        }
        
        public static string ReadWritePartition {
            get {
                return ResourceManager.GetString("ReadWritePartition", resourceCulture);
            }
        }
        
        public static string AdvancedActions {
            get {
                return ResourceManager.GetString("AdvancedActions", resourceCulture);
            }
        }
        
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        public static string ProvisionTooltip {
            get {
                return ResourceManager.GetString("ProvisionTooltip", resourceCulture);
            }
        }
        
        public static string RawProgramTooltip {
            get {
                return ResourceManager.GetString("RawProgramTooltip", resourceCulture);
            }
        }
    }
}
